/**
 * The local-Forem sweep's targets table (KTD5). Every path-and-method pair the
 * Composed spec declares appears here exactly once, as either a concrete request
 * or an explicit reason it is not exercised - the property that makes R4 and R5
 * checkable instead of aspirational.
 *
 * Exhaustive by construction: the table is generated by walking the spec's
 * operations, not hand-listed, so an operation cannot go missing. What is
 * hand-written is only the concrete request per operation.
 *
 * Two tables, not one. Reads key on the template alone; writes key on method and
 * template together, because `/api/badges/{id}` carries both a PATCH and a DELETE
 * and one recipe cannot serve both. Both halves stay pure functions of what the
 * run has discovered and created, so the ordered sequence in sweep-local.ts owns
 * all the state and this file owns none.
 *
 * Composed in memory from spec/api_v1.json + spec/overlay.json - never
 * spec/composed.json, which is gitignored and no CI step writes.
 */
import { opRouting } from "../src/generated/routing.ts";
import type { ReadSpec } from "./record-fixtures.ts";
import { composedSpec } from "./spec-keys.ts";

/**
 * Resources the write sequence creates. Their identifiers are not discoverable
 * before the run, so they arrive through the ledger (U6) folded into `Discovered.created`
 * rather than through a lookup - the table stays a pure function either way.
 */
export type Created =
  | "agentSession"
  | "article"
  | "badge"
  | "badgeAchievement"
  | "billboard"
  | "concept"
  | "organization"
  | "page"
  | "recommendedArticlesList"
  | "requestRedirect"
  | "segment"
  | "userIdentity";

/**
 * Why an operation was not exercised. `blocked` is pass one's only cause; the rest
 * name conditions the write half introduces, each of which a bare `blocked` would
 * flatten into an indistinguishable wall of "something was missing".
 */
export type Cause =
  /** No concrete request could be built: the template vanished, or discovery came up empty. */
  | "blocked"
  /** A create this operation depends on did not succeed, so its identifier never existed. */
  | "prerequisite-failed"
  /** The rung's credential is not configured on this machine (KTD6: a gap, not a crash). */
  | "tier-unavailable"
  /** Authorization refused the request at every rung of the ladder. */
  | "refused"
  /** The identifier exists in no ledger and the server says it does not exist. */
  | "target-not-found"
  /** The server rejected the request payload, which no amount of privilege fixes. */
  | "payload-rejected";

/** Values only a running instance can supply. Every field optional: a missing one degrades its operations to `blocked`, it never throws. */
export interface Discovered {
  articleId?: number;
  username?: string;
  slug?: string;
  userId?: number;
  userEmail?: string;
  organization?: string;
  organizationId?: number;
  commentId?: string;
  tag?: string;
  pageId?: number;
  badgeId?: number;
  badgeAchievementId?: number;
  billboardId?: number;
  conceptId?: number;
  segmentId?: number;
  surveyId?: string | number;
  trendId?: string | number;
  recommendedArticlesListId?: number;
  requestRedirectId?: number;
  agentSessionId?: string | number;
  analyticsStart?: string;
  /**
   * A seeded account the writes may suspend, retag and merge. Deliberately not a
   * rung account (R20): ten of the writes revoke roles or suspend, and aiming one
   * of those at the credential the rest of the run authenticates with would look
   * like a privilege finding rather than a self-inflicted wound.
   */
  targetUserId?: number;
  /** A second disposable account, since merge consumes the one it folds in. */
  mergeUserId?: number;
  /** Identifiers this run created, keyed by resource (U6's ledger, values only). */
  created?: Partial<Record<Created, string | number>>;
  /** Distinguishes one run's titles and slugs from the last; Forem rejects duplicates within a window. */
  runId?: string;
  /** Overrides the image URL the badge and organization creates hand the server (FOREM_IMAGE_URL). */
  imageUrl?: string;
}

export type SweepTarget =
  // `method` is optional on ReadSpec (the recorder defaults it to GET); the table
  // always sets it, so narrow it to required and every consumer can key on it.
  // `body` rides here rather than on ReadSpec: the recorder's spec type describes
  // reads, and the recorder has no use for a request body.
  // `fromLedger` marks an identifier this run created, which is what lets the
  // ladder read a 404 as a scoped refusal rather than as a missing target (F2).
  | ({ kind: "targeted"; method: string; body?: unknown; fromLedger?: boolean } & ReadSpec)
  | {
      kind: "skipped";
      template: string;
      method: string;
      cause: Cause;
      reason: string;
    };

type Request = {
  path: string;
  /**
   * The flat params object, placed as query or body by the generated routing
   * table (KTD7). Recipes never restate the placement the generator already knows.
   */
  params?: Record<string, unknown>;
  /** Explicit placement, valid only where the generator has no answer for the operation. */
  query?: Record<string, string | number>;
  body?: unknown;
  trim?: number;
  fromLedger?: boolean;
};
type Skip = { cause: Cause; reason: string };
type Resolved = Request | Skip;

const isSkip = (r: Resolved): r is Skip => "cause" in r;

/** A request that needs a discovered value; absent, the operation is blocked naming the field. */
const needs = <T>(value: T | undefined, field: string, build: (v: T) => Request): Resolved =>
  value === undefined
    ? { cause: "blocked", reason: `discovery unavailable: ${field}` }
    : build(value);

/**
 * A request against something the run itself created. Absent, the prerequisite
 * write failed - a distinct cause from discovery coming up empty, because the
 * fix is a working create rather than richer seed data.
 */
const made = (
  d: Discovered,
  resource: Created,
  build: (id: string | number) => Request,
): Resolved => {
  const id = d.created?.[resource];
  return id === undefined
    ? { cause: "prerequisite-failed", reason: `not created by this run: ${resource}` }
    : { ...build(id), fromLedger: true };
};

/** Per-run suffix, so a rerun inside Forem's duplicate-title window still creates. */
const tag = (d: Discovered): string => d.runId ?? "sweep";

/**
 * Badge and organization creation take an image URL the server downloads itself.
 * Pointing that at the instance under test keeps the run entirely local, which
 * is what makes it reproducible: an off-instance URL made both creates depend on
 * outbound HTTPS, and on a machine with partial IPv6 routing they failed on one
 * run and succeeded on the next.
 *
 * It needs the `skip_ssrf_protection` deviation documented in docs/local-forem.md,
 * because CarrierWave otherwise refuses any host resolving to a private address.
 */
export const DEFAULT_IMAGE_URL = "http://localhost:3000/assets/1.png";

/** Overridable, because whether that host is reachable is a property of the machine, not the spec. */
const image = (d: Discovered): string => d.imageUrl ?? DEFAULT_IMAGE_URL;

/**
 * One entry per GET template in the spec. Concrete-path style follows the
 * `publicReads` array in scripts/record-fixtures.ts - a pattern to copy, not an
 * import: that array is a local const inside the recorder's main guard.
 */
const READS: Record<string, (d: Discovered) => Resolved> = {
  "/api/agent_sessions": () => ({ path: "/api/agent_sessions" }),
  "/api/agent_sessions/{id}": (d) =>
    needs(d.agentSessionId, "agentSessionId", (id) => ({ path: `/api/agent_sessions/${id}` })),
  "/api/agent_sessions/{id}/raw_url": (d) =>
    needs(d.agentSessionId, "agentSessionId", (id) => ({
      path: `/api/agent_sessions/${id}/raw_url`,
    })),

  "/api/analytics/totals": () => ({ path: "/api/analytics/totals" }),
  "/api/analytics/historical": (d) =>
    needs(d.analyticsStart, "analyticsStart", (start) => ({
      path: "/api/analytics/historical",
      query: { start },
    })),
  "/api/analytics/past_day": () => ({ path: "/api/analytics/past_day" }),
  "/api/analytics/referrers": () => ({ path: "/api/analytics/referrers" }),
  "/api/analytics/top_contributors": () => ({ path: "/api/analytics/top_contributors" }),
  "/api/analytics/follower_engagement": () => ({ path: "/api/analytics/follower_engagement" }),
  "/api/analytics/dashboard": () => ({ path: "/api/analytics/dashboard" }),
  "/api/analytics/heatmap": () => ({ path: "/api/analytics/heatmap" }),

  "/api/articles": () => ({ path: "/api/articles" }),
  "/api/articles/search": () => ({ path: "/api/articles/search", query: { q: "a" } }),
  "/api/articles/semantic_search": () => ({
    path: "/api/articles/semantic_search",
    query: { q: "a" },
  }),
  "/api/articles/latest": () => ({ path: "/api/articles/latest" }),
  "/api/articles/{id}": (d) =>
    needs(d.articleId, "articleId", (id) => ({ path: `/api/articles/${id}` })),
  "/api/articles/{username}/{slug}": (d) =>
    d.username === undefined || d.slug === undefined
      ? {
          cause: "blocked",
          reason: `discovery unavailable: ${d.username === undefined ? "username" : "slug"}`,
        }
      : { path: `/api/articles/${d.username}/${d.slug}` },
  "/api/articles/me": () => ({ path: "/api/articles/me" }),
  "/api/articles/me/published": () => ({ path: "/api/articles/me/published" }),
  "/api/articles/me/unpublished": () => ({ path: "/api/articles/me/unpublished" }),
  "/api/articles/me/all": () => ({ path: "/api/articles/me/all" }),

  "/api/segments": () => ({ path: "/api/segments" }),
  "/api/segments/{id}": (d) =>
    needs(d.segmentId, "segmentId", (id) => ({ path: `/api/segments/${id}` })),
  "/api/segments/{id}/users": (d) =>
    needs(d.segmentId, "segmentId", (id) => ({ path: `/api/segments/${id}/users` })),

  "/api/badge_achievements": () => ({ path: "/api/badge_achievements" }),
  "/api/badge_achievements/{id}": (d) =>
    needs(d.badgeAchievementId, "badgeAchievementId", (id) => ({
      path: `/api/badge_achievements/${id}`,
    })),
  "/api/badges": () => ({ path: "/api/badges" }),
  "/api/badges/{id}": (d) => needs(d.badgeId, "badgeId", (id) => ({ path: `/api/badges/${id}` })),

  "/api/billboards": () => ({ path: "/api/billboards" }),
  "/api/billboards/{id}": (d) =>
    needs(d.billboardId, "billboardId", (id) => ({ path: `/api/billboards/${id}` })),

  "/api/comments": (d) =>
    needs(d.articleId, "articleId", (id) => ({ path: "/api/comments", query: { a_id: id } })),
  "/api/comments/{id}": (d) =>
    needs(d.commentId, "commentId", (id) => ({ path: `/api/comments/${id}` })),

  "/api/concepts": () => ({ path: "/api/concepts" }),
  "/api/concepts/search": () => ({ path: "/api/concepts/search", query: { q: "a" } }),
  "/api/concepts/{id}": (d) =>
    needs(d.conceptId, "conceptId", (id) => ({ path: `/api/concepts/${id}` })),
  "/api/concepts/{id}/articles": (d) =>
    needs(d.conceptId, "conceptId", (id) => ({ path: `/api/concepts/${id}/articles` })),
  "/api/admin/concepts": () => ({ path: "/api/admin/concepts" }),
  "/api/admin/concepts/{id}": (d) =>
    needs(d.conceptId, "conceptId", (id) => ({ path: `/api/admin/concepts/${id}` })),

  "/api/follows/tags": () => ({ path: "/api/follows/tags" }),
  "/api/followers/users": () => ({ path: "/api/followers/users" }),

  "/api/health_checks/app": () => ({ path: "/api/health_checks/app" }),
  "/api/health_checks/database": () => ({ path: "/api/health_checks/database" }),
  "/api/health_checks/cache": () => ({ path: "/api/health_checks/cache" }),

  "/api/instance": () => ({ path: "/api/instance" }),

  "/api/organizations": () => ({ path: "/api/organizations" }),
  "/api/organizations/{id}": (d) =>
    needs(d.organizationId, "organizationId", (id) => ({ path: `/api/organizations/${id}` })),
  "/api/organizations/{username}": (d) =>
    needs(d.organization, "organization", (u) => ({ path: `/api/organizations/${u}` })),
  "/api/organizations/{organization_id_or_username}/users": (d) =>
    needs(d.organization, "organization", (u) => ({ path: `/api/organizations/${u}/users` })),
  "/api/organizations/{organization_id_or_username}/articles": (d) =>
    needs(d.organization, "organization", (u) => ({ path: `/api/organizations/${u}/articles` })),

  // pages ships megabytes of body_html; the recorder trims it for the same reason
  "/api/pages": () => ({ path: "/api/pages", trim: 3 }),
  "/api/pages/{id}": (d) => needs(d.pageId, "pageId", (id) => ({ path: `/api/pages/${id}` })),

  "/api/podcast_episodes": () => ({ path: "/api/podcast_episodes" }),
  "/api/profile_images/{username}": (d) =>
    needs(d.username, "username", (u) => ({ path: `/api/profile_images/${u}` })),
  "/api/readinglist": () => ({ path: "/api/readinglist" }),

  "/api/recommended_articles_lists": () => ({ path: "/api/recommended_articles_lists" }),
  "/api/recommended_articles_lists/{id}": (d) =>
    needs(d.recommendedArticlesListId, "recommendedArticlesListId", (id) => ({
      path: `/api/recommended_articles_lists/${id}`,
    })),

  "/api/admin/request_redirects": () => ({ path: "/api/admin/request_redirects" }),
  "/api/admin/request_redirects/{id}": (d) =>
    needs(d.requestRedirectId, "requestRedirectId", (id) => ({
      path: `/api/admin/request_redirects/${id}`,
    })),

  "/api/subforems": () => ({ path: "/api/subforems" }),

  "/api/surveys": () => ({ path: "/api/surveys" }),
  "/api/surveys/{id_or_slug}": (d) =>
    needs(d.surveyId, "surveyId", (id) => ({ path: `/api/surveys/${id}` })),
  "/api/surveys/{id_or_slug}/poll_votes": (d) =>
    needs(d.surveyId, "surveyId", (id) => ({ path: `/api/surveys/${id}/poll_votes` })),
  "/api/surveys/{id_or_slug}/poll_text_responses": (d) =>
    needs(d.surveyId, "surveyId", (id) => ({ path: `/api/surveys/${id}/poll_text_responses` })),

  "/api/tags": () => ({ path: "/api/tags" }),

  "/api/trends": () => ({ path: "/api/trends" }),
  "/api/trends/{id_or_slug}": (d) =>
    needs(d.trendId, "trendId", (id) => ({ path: `/api/trends/${id}` })),
  "/api/trends/{trend_id_or_slug}/articles": (d) =>
    needs(d.trendId, "trendId", (id) => ({ path: `/api/trends/${id}/articles` })),

  "/api/users/me": () => ({ path: "/api/users/me" }),
  "/api/users/search": (d) =>
    needs(d.userEmail, "userEmail", (email) => ({ path: "/api/users/search", query: { email } })),
  "/api/users/{id}": (d) => needs(d.userId, "userId", (id) => ({ path: `/api/users/${id}` })),
  "/api/admin/users": () => ({ path: "/api/admin/users" }),
  "/api/admin/users/{id}": (d) =>
    needs(d.userId, "userId", (id) => ({ path: `/api/admin/users/${id}` })),
  "/api/admin/users/{user_id}/notes": (d) =>
    needs(d.userId, "userId", (id) => ({ path: `/api/admin/users/${id}/notes` })),
  "/api/admin/users/{user_id}/identities": (d) =>
    needs(d.userId, "userId", (id) => ({ path: `/api/admin/users/${id}/identities` })),

  "/api/videos": () => ({ path: "/api/videos" }),
};

/**
 * One entry per non-GET operation, keyed by method and template together (KTD2):
 * `/api/badges/{id}` alone carries both a PATCH and a DELETE, and a template-keyed
 * table would silently serve one recipe to both.
 *
 * Recipes hand back a flat `params` object wherever the generated routing table
 * knows where it goes; only the operations the generator omits - the deletes and
 * the parameterless verbs - name `query` or `body` themselves.
 */
const WRITES: Record<string, (d: Discovered) => Resolved> = {
  "POST /api/agent_sessions": (d) => ({
    path: "/api/agent_sessions",
    params: {
      title: `sweep session ${tag(d)}`,
      curated_data: JSON.stringify({ messages: [], metadata: { source: "devto-client sweep" } }),
      tool_name: "claude_code",
    },
  }),
  "POST /api/agent_sessions/presign": () => ({ path: "/api/agent_sessions/presign" }),

  "POST /api/articles": (d) => ({
    path: "/api/articles",
    params: {
      article: {
        // unique per run: Forem rejects a duplicate title within a short window,
        // the same trap the fixture recorder already works around
        title: `Sweep probe ${tag(d)}`,
        body_markdown: "Created by the devto-client local sweep.",
        published: false,
      },
    },
  }),
  "PUT /api/articles/{id}": (d) =>
    made(d, "article", (id) => ({
      path: `/api/articles/${id}`,
      // published, because `revoke_publication?` refuses an unpublished article at
      // every rung, which would leave the unpublish probe permanently refused
      params: { article: { body_markdown: `Updated by the sweep ${tag(d)}.`, published: true } },
    })),
  "PUT /api/articles/{id}/unpublish": (d) =>
    made(d, "article", (id) => ({
      path: `/api/articles/${id}/unpublish`,
      params: { note: `sweep ${tag(d)}` },
    })),

  "POST /api/segments": () => ({ path: "/api/segments" }),
  "PUT /api/segments/{id}/add_users": (d) =>
    made(d, "segment", (id) =>
      d.targetUserId === undefined
        ? { path: `/api/segments/${id}/add_users`, params: { user_ids: [] } }
        : { path: `/api/segments/${id}/add_users`, params: { user_ids: [d.targetUserId] } },
    ),
  "PUT /api/segments/{id}/remove_users": (d) =>
    made(d, "segment", (id) =>
      d.targetUserId === undefined
        ? { path: `/api/segments/${id}/remove_users`, params: { user_ids: [] } }
        : { path: `/api/segments/${id}/remove_users`, params: { user_ids: [d.targetUserId] } },
    ),
  "DELETE /api/segments/{id}": (d) => made(d, "segment", (id) => ({ path: `/api/segments/${id}` })),

  "POST /api/badges": (d) => ({
    path: "/api/badges",
    params: {
      badge: {
        title: `Sweep badge ${tag(d)}`,
        description: "Created by the devto-client local sweep.",
        remote_badge_image_url: image(d),
      },
    },
  }),
  "PATCH /api/badges/{id}": (d) =>
    made(d, "badge", (id) => ({
      path: `/api/badges/${id}`,
      params: { badge: { description: `Updated by the sweep ${tag(d)}.` } },
    })),
  "DELETE /api/badges/{id}": (d) => made(d, "badge", (id) => ({ path: `/api/badges/${id}` })),

  "POST /api/badge_achievements": (d) => {
    const badgeId = d.created?.badge ?? d.badgeId;
    if (badgeId === undefined) {
      return { cause: "prerequisite-failed", reason: "not created by this run: badge" };
    }
    return needs(d.targetUserId, "targetUserId", (userId) => ({
      path: "/api/badge_achievements",
      params: { badge_achievement: { user_id: userId, badge_id: badgeId } },
    }));
  },
  "DELETE /api/badge_achievements/{id}": (d) =>
    made(d, "badgeAchievement", (id) => ({ path: `/api/badge_achievements/${id}` })),

  "POST /api/billboards": (d) => ({
    path: "/api/billboards",
    params: {
      name: `Sweep billboard ${tag(d)}`,
      body_markdown: "Created by the devto-client local sweep.",
      placement_area: "sidebar_right",
      published: false,
      approved: false,
    },
  }),
  "PUT /api/billboards/{id}": (d) =>
    made(d, "billboard", (id) => ({
      path: `/api/billboards/${id}`,
      params: { body_markdown: `Updated by the sweep ${tag(d)}.` },
    })),
  "PUT /api/billboards/{id}/unpublish": (d) =>
    made(d, "billboard", (id) => ({ path: `/api/billboards/${id}/unpublish` })),

  "POST /api/admin/concepts": (d) => ({
    path: "/api/admin/concepts",
    params: { concept: { name: `sweep-concept-${tag(d)}` } },
  }),
  "PATCH /api/admin/concepts/{id}": (d) =>
    made(d, "concept", (id) => ({
      path: `/api/admin/concepts/${id}`,
      params: { concept: { description: `Updated by the sweep ${tag(d)}.` } },
    })),
  "PATCH /api/concepts/{id}": (d) =>
    made(d, "concept", (id) => ({
      path: `/api/concepts/${id}`,
      params: { concept: { description: `Updated by the sweep ${tag(d)}.` } },
    })),
  "POST /api/admin/concepts/{id}/trigger_lookback": (d) =>
    made(d, "concept", (id) => ({
      path: `/api/admin/concepts/${id}/trigger_lookback`,
      params: { days: 1 },
    })),
  "DELETE /api/admin/concepts/{id}": (d) =>
    made(d, "concept", (id) => ({ path: `/api/admin/concepts/${id}` })),

  // no GET anywhere in the spec renders a feedback message, so nothing in the run
  // can produce this identifier - the honest answer is a cause, not a guessed id
  "PATCH /api/feedback_messages/{id}": () => ({
    cause: "blocked",
    reason:
      "discovery unavailable: feedbackMessageId (no operation in the spec lists or creates one)",
  }),

  "POST /api/follows": (d) =>
    needs(d.targetUserId, "targetUserId", (id) => ({
      path: "/api/follows",
      params: { user_ids: [id] },
    })),

  // wrapped, because the controller reads `params.require(:organization)` while
  // the spec declares the fields flat - a spec defect the run reports separately
  "POST /api/organizations": (d) => ({
    path: "/api/organizations",
    params: {
      organization: {
        name: `Sweep Org ${tag(d)}`,
        slug: `sweeporg${tag(d)}`.replace(/[^a-z0-9]/g, "").slice(0, 30),
        summary: "Created by the devto-client local sweep.",
        url: "https://example.com",
        // `Images::SafeRemoteProfileImageUrl` rewrites any http value to https
        // before handing it to the downloader, and a loopback instance serves no
        // TLS - so this create needs an outbound-reachable https image and fails
        // deterministically without one. Point FOREM_IMAGE_URL at one to exercise
        // it; the run reports the gap rather than guessing what it would return.
        profile_image: image(d),
      },
    },
  }),
  "PUT /api/organizations/{id}": (d) =>
    made(d, "organization", (id) => ({
      path: `/api/organizations/${id}`,
      params: { organization: { summary: `Updated by the sweep ${tag(d)}.` } },
    })),
  "DELETE /api/organizations/{id}": (d) =>
    made(d, "organization", (id) => ({ path: `/api/organizations/${id}` })),

  "POST /api/pages": (d) => ({
    path: "/api/pages",
    params: {
      title: `Sweep page ${tag(d)}`,
      slug: `sweep-page-${tag(d)}`,
      description: "Created by the devto-client local sweep.",
      body_markdown: "Created by the devto-client local sweep.",
      template: "contained",
    },
  }),
  "PUT /api/pages/{id}": (d) =>
    made(d, "page", (id) => ({
      path: `/api/pages/${id}`,
      params: { body_markdown: `Updated by the sweep ${tag(d)}.` },
    })),
  "DELETE /api/pages/{id}": (d) => made(d, "page", (id) => ({ path: `/api/pages/${id}` })),

  "POST /api/reactions": (d) =>
    needs(d.articleId, "articleId", (id) => ({
      path: "/api/reactions",
      params: { category: "like", reactable_id: id, reactable_type: "Article" },
    })),
  "POST /api/reactions/toggle": (d) =>
    needs(d.articleId, "articleId", (id) => ({
      path: "/api/reactions/toggle",
      params: { category: "like", reactable_id: id, reactable_type: "Article" },
    })),

  "POST /api/recommended_articles_lists": (d) =>
    needs(d.targetUserId, "targetUserId", (userId) => ({
      path: "/api/recommended_articles_lists",
      params: {
        name: `Sweep list ${tag(d)}`,
        placement_area: "main_feed",
        user_id: userId,
        ...(d.articleId === undefined ? {} : { article_ids: [d.articleId] }),
      },
    })),
  "PATCH /api/recommended_articles_lists/{id}": (d) =>
    made(d, "recommendedArticlesList", (id) => ({
      path: `/api/recommended_articles_lists/${id}`,
      params: { name: `Sweep list ${tag(d)} updated` },
    })),

  "POST /api/admin/request_redirects": (d) => ({
    path: "/api/admin/request_redirects",
    params: {
      request_redirect: {
        original_url: `/sweep-${tag(d)}`,
        destination_url: "https://example.com/destination",
        request_domain: "example.com",
      },
    },
  }),
  "PATCH /api/admin/request_redirects/{id}": (d) =>
    made(d, "requestRedirect", (id) => ({
      path: `/api/admin/request_redirects/${id}`,
      params: { request_redirect: { destination_url: `https://example.com/${tag(d)}` } },
    })),
  "DELETE /api/admin/request_redirects/{id}": (d) =>
    made(d, "requestRedirect", (id) => ({ path: `/api/admin/request_redirects/${id}` })),

  "POST /api/admin/users": (d) => ({
    path: "/api/admin/users",
    params: { email: `sweep-invite-${tag(d)}@example.com`, name: `Sweep Invite ${tag(d)}` },
  }),
  "PATCH /api/admin/users/{id}": (d) =>
    needs(d.targetUserId, "targetUserId", (id) => ({
      path: `/api/admin/users/${id}`,
      params: { summary: `Updated by the sweep ${tag(d)}.` },
    })),
  "PUT /api/admin/users/{id}/email": (d) =>
    needs(d.targetUserId, "targetUserId", (id) => ({
      path: `/api/admin/users/${id}/email`,
      params: { email: `sweep-${tag(d)}-${id}@example.com` },
    })),
  "PUT /api/admin/users/{id}/status": (d) =>
    needs(d.targetUserId, "targetUserId", (id) => ({
      path: `/api/admin/users/${id}/status`,
      params: { status: "Good standing", note: `sweep ${tag(d)}` },
    })),
  "PUT /api/admin/users/{id}/notification_settings": (d) =>
    needs(d.targetUserId, "targetUserId", (id) => ({
      path: `/api/admin/users/${id}/notification_settings`,
      params: { notification_setting: { email_newsletter: false } },
    })),
  "POST /api/admin/users/{user_id}/notes": (d) =>
    needs(d.targetUserId, "targetUserId", (id) => ({
      path: `/api/admin/users/${id}/notes`,
      params: { content: `Sweep note ${tag(d)}`, reason: "sweep" },
    })),
  "POST /api/admin/users/{user_id}/identities": (d) =>
    needs(d.targetUserId, "targetUserId", (id) => ({
      path: `/api/admin/users/${id}/identities`,
      params: { provider: "github", uid: `sweep-${tag(d)}-${id}`, username: `sweep${id}` },
    })),
  "DELETE /api/admin/users/{user_id}/identities/{id}": (d) => {
    const userId = d.targetUserId;
    if (userId === undefined) {
      return { cause: "blocked", reason: "discovery unavailable: targetUserId" };
    }
    return made(d, "userIdentity", (id) => ({
      path: `/api/admin/users/${userId}/identities/${id}`,
    }));
  },
  "POST /api/admin/users/identities/bulk": (d) =>
    needs(d.targetUserId, "targetUserId", (id) => ({
      path: "/api/admin/users/identities/bulk",
      params: { provider: "github", identities: [{ user_id: id, uid: `sweep-bulk-${tag(d)}` }] },
    })),
  // merge consumes the account it folds in, which is why it takes the second
  // disposable user rather than reusing the one every other write already touched
  "POST /api/admin/users/{id}/merge": (d) =>
    d.targetUserId === undefined || d.mergeUserId === undefined
      ? {
          cause: "blocked",
          reason: `discovery unavailable: ${d.targetUserId === undefined ? "targetUserId" : "mergeUserId"}`,
        }
      : {
          path: `/api/admin/users/${d.targetUserId}/merge`,
          params: { merge_user_id: d.mergeUserId },
        },

  "PUT /api/users/{id}/suspend": (d) =>
    needs(d.targetUserId, "targetUserId", (id) => ({ path: `/api/users/${id}/suspend` })),
  "PUT /api/users/{id}/limited": (d) =>
    needs(d.targetUserId, "targetUserId", (id) => ({ path: `/api/users/${id}/limited` })),
  "DELETE /api/users/{id}/limited": (d) =>
    needs(d.targetUserId, "targetUserId", (id) => ({ path: `/api/users/${id}/limited` })),
  "PUT /api/users/{id}/spam": (d) =>
    needs(d.targetUserId, "targetUserId", (id) => ({ path: `/api/users/${id}/spam` })),
  "DELETE /api/users/{id}/spam": (d) =>
    needs(d.targetUserId, "targetUserId", (id) => ({ path: `/api/users/${id}/spam` })),
  "PUT /api/users/{id}/trusted": (d) =>
    needs(d.targetUserId, "targetUserId", (id) => ({ path: `/api/users/${id}/trusted` })),
  "DELETE /api/users/{id}/trusted": (d) =>
    needs(d.targetUserId, "targetUserId", (id) => ({ path: `/api/users/${id}/trusted` })),
  "PUT /api/users/{id}/unpublish": (d) =>
    needs(d.targetUserId, "targetUserId", (id) => ({ path: `/api/users/${id}/unpublish` })),
};

/** GET templates the table knows how to request; exported so a test can hold it to the spec. */
export const readTemplates = (): string[] => Object.keys(READS);

/** `METHOD /template` keys the write table covers; the mirror of `readTemplates`. */
export const writeOperations = (): string[] => Object.keys(WRITES);

/** Every path-and-method pair the spec declares, in spec order. */
export function specOperations(): { template: string; method: string }[] {
  const methods = new Set(["get", "post", "put", "delete", "patch"]);
  const out: { template: string; method: string }[] = [];
  for (const [template, item] of Object.entries(composedSpec().paths)) {
    for (const method of Object.keys(item)) {
      if (methods.has(method)) out.push({ template, method: method.toUpperCase() });
    }
  }
  return out;
}

/**
 * Where an operation's flat params object belongs, per the generated routing
 * table (KTD7). The generator omits operations that take no params object, which
 * is why this can answer `undefined` - those recipes state their own placement.
 */
export const paramPlacement = (template: string, method: string): "query" | "body" | undefined =>
  opRouting[`${method.toLowerCase()} ${template}`];

/**
 * The targets table: a pure function of what the run managed to discover and of
 * what it has created so far. An operation whose identifier is absent becomes a
 * cause naming what it lacked, which is AE3's "reported, never silently skipped".
 */
export function buildTargets(discovered: Discovered): SweepTarget[] {
  return specOperations().map(({ template, method }) => {
    const build = method === "GET" ? READS[template] : WRITES[`${method} ${template}`];
    if (!build) {
      return {
        kind: "skipped",
        template,
        method,
        cause: "blocked",
        reason: "no sweep target defined for this operation",
      };
    }
    const resolved = build(discovered);
    if (isSkip(resolved)) {
      return { kind: "skipped", template, method, cause: resolved.cause, reason: resolved.reason };
    }
    const target: {
      kind: "targeted";
      method: string;
      body?: unknown;
      fromLedger?: boolean;
    } & ReadSpec = {
      kind: "targeted",
      template,
      method,
      path: resolved.path,
    };
    if (resolved.query) target.query = resolved.query;
    if (resolved.body !== undefined) target.body = resolved.body;
    if (resolved.params) {
      // the generator, not the recipe, decides placement wherever it has an answer
      if (paramPlacement(template, method) === "query") {
        target.query = resolved.params as Record<string, string | number>;
      } else {
        target.body = resolved.params;
      }
    }
    if (resolved.trim !== undefined) target.trim = resolved.trim;
    if (resolved.fromLedger) target.fromLedger = true;
    return target;
  });
}
