/**
 * The local-Forem sweep's targets table (KTD5). Every path-and-method pair the
 * Composed spec declares appears here exactly once, as either a concrete request
 * or an explicit reason it is not exercised - the property that makes R4 and R5
 * checkable instead of aspirational.
 *
 * Exhaustive by construction: the table is generated by walking the spec's
 * operations, not hand-listed, so an operation cannot go missing. What is
 * hand-written is only the concrete request for each GET template.
 *
 * Composed in memory from spec/api_v1.json + spec/overlay.json - never
 * spec/composed.json, which is gitignored and no CI step writes.
 */
import type { ReadSpec } from "./record-fixtures.ts";
import { composedSpec } from "./spec-keys.ts";

/** Values only a running instance can supply. Every field optional: a missing one degrades its operations to `blocked`, it never throws. */
export interface Discovered {
  articleId?: number;
  username?: string;
  slug?: string;
  userId?: number;
  userEmail?: string;
  organization?: string;
  organizationId?: number;
  commentId?: string;
  tag?: string;
  pageId?: number;
  badgeId?: number;
  badgeAchievementId?: number;
  billboardId?: number;
  conceptId?: number;
  segmentId?: number;
  surveyId?: string | number;
  trendId?: string | number;
  recommendedArticlesListId?: number;
  requestRedirectId?: number;
  agentSessionId?: string | number;
  analyticsStart?: string;
}

export type SweepTarget =
  // `method` is optional on ReadSpec (the recorder defaults it to GET); the table
  // always sets it, so narrow it to required and every consumer can key on it.
  | ({ kind: "targeted"; method: string } & ReadSpec)
  | {
      kind: "skipped";
      template: string;
      method: string;
      cause: "blocked" | "deferred";
      reason: string;
    };

type Request = { path: string; query?: Record<string, string | number>; trim?: number };
type Resolved = Request | { blocked: string };

/** A request that needs a discovered value; absent, the operation is blocked naming the field. */
const needs = <T>(
  value: T | undefined,
  field: keyof Discovered,
  build: (v: T) => Request,
): Resolved =>
  value === undefined ? { blocked: `discovery unavailable: ${field}` } : build(value);

/**
 * One entry per GET template in the spec. Concrete-path style follows the
 * `publicReads` array in scripts/record-fixtures.ts - a pattern to copy, not an
 * import: that array is a local const inside the recorder's main guard.
 */
const READS: Record<string, (d: Discovered) => Resolved> = {
  "/api/agent_sessions": () => ({ path: "/api/agent_sessions" }),
  "/api/agent_sessions/{id}": (d) =>
    needs(d.agentSessionId, "agentSessionId", (id) => ({ path: `/api/agent_sessions/${id}` })),
  "/api/agent_sessions/{id}/raw_url": (d) =>
    needs(d.agentSessionId, "agentSessionId", (id) => ({
      path: `/api/agent_sessions/${id}/raw_url`,
    })),

  "/api/analytics/totals": () => ({ path: "/api/analytics/totals" }),
  "/api/analytics/historical": (d) =>
    needs(d.analyticsStart, "analyticsStart", (start) => ({
      path: "/api/analytics/historical",
      query: { start },
    })),
  "/api/analytics/past_day": () => ({ path: "/api/analytics/past_day" }),
  "/api/analytics/referrers": () => ({ path: "/api/analytics/referrers" }),
  "/api/analytics/top_contributors": () => ({ path: "/api/analytics/top_contributors" }),
  "/api/analytics/follower_engagement": () => ({ path: "/api/analytics/follower_engagement" }),
  "/api/analytics/dashboard": () => ({ path: "/api/analytics/dashboard" }),
  "/api/analytics/heatmap": () => ({ path: "/api/analytics/heatmap" }),

  "/api/articles": () => ({ path: "/api/articles" }),
  "/api/articles/search": () => ({ path: "/api/articles/search", query: { q: "a" } }),
  "/api/articles/semantic_search": () => ({
    path: "/api/articles/semantic_search",
    query: { q: "a" },
  }),
  "/api/articles/latest": () => ({ path: "/api/articles/latest" }),
  "/api/articles/{id}": (d) =>
    needs(d.articleId, "articleId", (id) => ({ path: `/api/articles/${id}` })),
  "/api/articles/{username}/{slug}": (d) =>
    d.username === undefined || d.slug === undefined
      ? { blocked: `discovery unavailable: ${d.username === undefined ? "username" : "slug"}` }
      : { path: `/api/articles/${d.username}/${d.slug}` },
  "/api/articles/me": () => ({ path: "/api/articles/me" }),
  "/api/articles/me/published": () => ({ path: "/api/articles/me/published" }),
  "/api/articles/me/unpublished": () => ({ path: "/api/articles/me/unpublished" }),
  "/api/articles/me/all": () => ({ path: "/api/articles/me/all" }),

  "/api/segments": () => ({ path: "/api/segments" }),
  "/api/segments/{id}": (d) =>
    needs(d.segmentId, "segmentId", (id) => ({ path: `/api/segments/${id}` })),
  "/api/segments/{id}/users": (d) =>
    needs(d.segmentId, "segmentId", (id) => ({ path: `/api/segments/${id}/users` })),

  "/api/badge_achievements": () => ({ path: "/api/badge_achievements" }),
  "/api/badge_achievements/{id}": (d) =>
    needs(d.badgeAchievementId, "badgeAchievementId", (id) => ({
      path: `/api/badge_achievements/${id}`,
    })),
  "/api/badges": () => ({ path: "/api/badges" }),
  "/api/badges/{id}": (d) => needs(d.badgeId, "badgeId", (id) => ({ path: `/api/badges/${id}` })),

  "/api/billboards": () => ({ path: "/api/billboards" }),
  "/api/billboards/{id}": (d) =>
    needs(d.billboardId, "billboardId", (id) => ({ path: `/api/billboards/${id}` })),

  "/api/comments": (d) =>
    needs(d.articleId, "articleId", (id) => ({ path: "/api/comments", query: { a_id: id } })),
  "/api/comments/{id}": (d) =>
    needs(d.commentId, "commentId", (id) => ({ path: `/api/comments/${id}` })),

  "/api/concepts": () => ({ path: "/api/concepts" }),
  "/api/concepts/search": () => ({ path: "/api/concepts/search", query: { q: "a" } }),
  "/api/concepts/{id}": (d) =>
    needs(d.conceptId, "conceptId", (id) => ({ path: `/api/concepts/${id}` })),
  "/api/concepts/{id}/articles": (d) =>
    needs(d.conceptId, "conceptId", (id) => ({ path: `/api/concepts/${id}/articles` })),
  "/api/admin/concepts": () => ({ path: "/api/admin/concepts" }),
  "/api/admin/concepts/{id}": (d) =>
    needs(d.conceptId, "conceptId", (id) => ({ path: `/api/admin/concepts/${id}` })),

  "/api/follows/tags": () => ({ path: "/api/follows/tags" }),
  "/api/followers/users": () => ({ path: "/api/followers/users" }),

  "/api/health_checks/app": () => ({ path: "/api/health_checks/app" }),
  "/api/health_checks/database": () => ({ path: "/api/health_checks/database" }),
  "/api/health_checks/cache": () => ({ path: "/api/health_checks/cache" }),

  "/api/instance": () => ({ path: "/api/instance" }),

  "/api/organizations": () => ({ path: "/api/organizations" }),
  "/api/organizations/{id}": (d) =>
    needs(d.organizationId, "organizationId", (id) => ({ path: `/api/organizations/${id}` })),
  "/api/organizations/{username}": (d) =>
    needs(d.organization, "organization", (u) => ({ path: `/api/organizations/${u}` })),
  "/api/organizations/{organization_id_or_username}/users": (d) =>
    needs(d.organization, "organization", (u) => ({ path: `/api/organizations/${u}/users` })),
  "/api/organizations/{organization_id_or_username}/articles": (d) =>
    needs(d.organization, "organization", (u) => ({ path: `/api/organizations/${u}/articles` })),

  // pages ships megabytes of body_html; the recorder trims it for the same reason
  "/api/pages": () => ({ path: "/api/pages", trim: 3 }),
  "/api/pages/{id}": (d) => needs(d.pageId, "pageId", (id) => ({ path: `/api/pages/${id}` })),

  "/api/podcast_episodes": () => ({ path: "/api/podcast_episodes" }),
  "/api/profile_images/{username}": (d) =>
    needs(d.username, "username", (u) => ({ path: `/api/profile_images/${u}` })),
  "/api/readinglist": () => ({ path: "/api/readinglist" }),

  "/api/recommended_articles_lists": () => ({ path: "/api/recommended_articles_lists" }),
  "/api/recommended_articles_lists/{id}": (d) =>
    needs(d.recommendedArticlesListId, "recommendedArticlesListId", (id) => ({
      path: `/api/recommended_articles_lists/${id}`,
    })),

  "/api/admin/request_redirects": () => ({ path: "/api/admin/request_redirects" }),
  "/api/admin/request_redirects/{id}": (d) =>
    needs(d.requestRedirectId, "requestRedirectId", (id) => ({
      path: `/api/admin/request_redirects/${id}`,
    })),

  "/api/subforems": () => ({ path: "/api/subforems" }),

  "/api/surveys": () => ({ path: "/api/surveys" }),
  "/api/surveys/{id_or_slug}": (d) =>
    needs(d.surveyId, "surveyId", (id) => ({ path: `/api/surveys/${id}` })),
  "/api/surveys/{id_or_slug}/poll_votes": (d) =>
    needs(d.surveyId, "surveyId", (id) => ({ path: `/api/surveys/${id}/poll_votes` })),
  "/api/surveys/{id_or_slug}/poll_text_responses": (d) =>
    needs(d.surveyId, "surveyId", (id) => ({ path: `/api/surveys/${id}/poll_text_responses` })),

  "/api/tags": () => ({ path: "/api/tags" }),

  "/api/trends": () => ({ path: "/api/trends" }),
  "/api/trends/{id_or_slug}": (d) =>
    needs(d.trendId, "trendId", (id) => ({ path: `/api/trends/${id}` })),
  "/api/trends/{trend_id_or_slug}/articles": (d) =>
    needs(d.trendId, "trendId", (id) => ({ path: `/api/trends/${id}/articles` })),

  "/api/users/me": () => ({ path: "/api/users/me" }),
  "/api/users/search": (d) =>
    needs(d.userEmail, "userEmail", (email) => ({ path: "/api/users/search", query: { email } })),
  "/api/users/{id}": (d) => needs(d.userId, "userId", (id) => ({ path: `/api/users/${id}` })),
  "/api/admin/users": () => ({ path: "/api/admin/users" }),
  "/api/admin/users/{id}": (d) =>
    needs(d.userId, "userId", (id) => ({ path: `/api/admin/users/${id}` })),
  "/api/admin/users/{user_id}/notes": (d) =>
    needs(d.userId, "userId", (id) => ({ path: `/api/admin/users/${id}/notes` })),
  "/api/admin/users/{user_id}/identities": (d) =>
    needs(d.userId, "userId", (id) => ({ path: `/api/admin/users/${id}/identities` })),

  "/api/videos": () => ({ path: "/api/videos" }),
};

/** GET templates the table knows how to request; exported so a test can hold it to the spec. */
export const readTemplates = (): string[] => Object.keys(READS);

/** Every path-and-method pair the spec declares, in spec order. */
export function specOperations(): { template: string; method: string }[] {
  const methods = new Set(["get", "post", "put", "delete", "patch"]);
  const out: { template: string; method: string }[] = [];
  for (const [template, item] of Object.entries(composedSpec().paths)) {
    for (const method of Object.keys(item)) {
      if (methods.has(method)) out.push({ template, method: method.toUpperCase() });
    }
  }
  return out;
}

/**
 * The targets table: a pure function of what the run managed to discover.
 * Writes are all deferred per KTD4; a GET whose discoverable is absent becomes
 * blocked naming the field, which is AE3's "reported, never silently skipped".
 */
export function buildTargets(discovered: Discovered): SweepTarget[] {
  return specOperations().map(({ template, method }) => {
    if (method !== "GET") {
      return {
        kind: "skipped",
        template,
        method,
        cause: "deferred",
        reason: "write operation; pass one is reads only (KTD4)",
      };
    }
    const build = READS[template];
    if (!build) {
      return {
        kind: "skipped",
        template,
        method,
        cause: "blocked",
        reason: "no sweep target defined for this operation",
      };
    }
    const resolved = build(discovered);
    if ("blocked" in resolved) {
      return { kind: "skipped", template, method, cause: "blocked", reason: resolved.blocked };
    }
    const target: { kind: "targeted"; method: string } & ReadSpec = {
      kind: "targeted",
      template,
      method,
      path: resolved.path,
    };
    if (resolved.query) target.query = resolved.query;
    if (resolved.trim !== undefined) target.trim = resolved.trim;
    return target;
  });
}
